### PR TITLE
fix: align cookie implementation with express-session

### LINKED ISSUE #176: What is the reason behind converting the `cookie.maxAge` prop to an `Expires` value in the actual cookie?
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

`getCookieOpts()` always converts the `maxAge` property to the `expires` property by creating a new Date and adding the `maxAge` to the current server's time. The returned object omits the `maxAge` property then. I believe this creates issues if the client's time is out of sync and goes against the expected behavior.

What is the rationale behind this design choice? To be honest, I hope the answer is not just "because express does it the same way" 😅

### PR DESCRIPTION
**Pull request by climba03003**
Fixes #176 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
I dont think this is correct. originalMaxAge is used internally.

@rclmenezes

**Comment by climba03003** [comment]
> I dont think this is correct. originalMaxAge is used internally.

It still used internally, nothing is changed.

**Review by SimenB — APPROVED** [review]
I think this makes sense 👍

**Comment by rclmenezes** [comment]
LGTM

@Uzlopak the key comment is here: https://github.com/fastify/session/issues/176#issuecomment-1283921462

I confirmed myself that express-session does _not_ set `expired` every time in the store, so this behavior is consistent.

Also, looks like express-session uses originalMaxAge the same way:
https://github.com/expressjs/session/search?q=originalmaxage

Nice PR

**Review by Uzlopak — APPROVED** [review]

**Pull request merged**
