### PR TITLE
rename session to fastifySession

### PR DESCRIPTION
**Pull request by Uzlopak**
Something which really annoyed me from the beginning :)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
Please stop merging pull requests without review. In this particular case, I don't see a need for the change. We know it's a Fastify plugin. There's no need for the `fastify` prefix on the function name.

**Comment by Uzlopak** [comment]
I think it is a useful change. We have another file called session.js where we have a Session-Class. Now I have a better clarity regarding naming inside.

**Comment by zekth** [comment]
> I think it is a useful change. We have another file called session.js where we have a Session-Class. Now I have a better clarity regarding naming inside.

Even if you think that's a useful change, you should wait for a review.

**Comment by Uzlopak** [comment]
ok

**Pull request merged**
