### PR TITLE
Simplify shouldSaveSession code a little bit

### PR DESCRIPTION
**Pull request by rclmenezes**
No noticeable benchmark change.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Uzlopak — CHANGES_REQUESTED** [review]
Currently watching a movie. Please wait for the review

**Comment by Uzlopak** [comment]
I have a local branch, were I even did it more extreme

```js
  function isConnectionSecure (request) {
    return (
      request.raw.socket?.encrypted === true ||
      request.headers['x-forwarded-proto'] === 'https'
    )
  }

  function shouldSaveSession (request, cookieOpts, saveUninitialized) {
    if (!saveUninitialized && !request.session.isModified()) {
      return false
    }
    if (cookieOpts.secure !== true || cookieOpts.secure === 'auto') {
      return true
    }
    return isConnectionSecure(request)
  }
```

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
