### PR TITLE
fix: idGenerator isn't in the options type.

### PR DESCRIPTION
**Pull request by rubybb**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by zekth** [comment]
Could you please add types test on it? thanks

**Comment by rubybb** [comment]
> Could you please add types test on it? thanks

Not sure how.

**Comment by mcollina** [comment]
Could you add a test for the type? Just use the new option in https://github.com/fastify/session/blob/master/types/types.test-d.ts

**Comment by rubybb** [comment]
> Could you add a test for the type? Just use the new option in https://github.com/fastify/session/blob/master/types/types.test-d.ts

Is that good? Also we can add the ``hacktoberfest`` tag to this repository?
For more information: https://hacktoberfest.digitalocean.com/

**Review by mcollina — APPROVED** [review]
lgtm

**Review by zekth — APPROVED** [review]
LGTM thanks!

**Pull request merged**
