### PR TITLE
feat: Promise API

### LINKED ISSUE #24: Promise API
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently `SessionStore` (and `request.destroySession`) are callback APIs. Ideally these should be Promise-based instead (or support both if you want to keep that).

Since adaptors (such as `connect-redis`) all expect callback APIs, that API probably has to be kept at least as backing implementation. So dual API (like Fastify itself) probably makes sense.

### Motivation

It's more ergonomic, especially in larger async functions.

### Example

Instead of

```js
await promisify(sessionStore.set.bind(sessionStore))(
  session.sessionId,
  session,
);

//

await promisify(sessionStore.destroy.bind(sessionStore))(session.sessionId);
```

we could do

```js
await sessionStore.set(session.sessionId, session);

//

await sessionStore.destroy(session.sessionId);
```

### PR DESCRIPTION
**Pull request by SimenB**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Fixes #24.

~(note that this includes #77, so just review the last commit)~

### CODE REVIEW

**Comment by mcollina** [comment]
what's the semversiness of this?

**Comment by SimenB** [comment]
I'd say this is a minor, but #77 is major so they can be bundled together in a new release

**Review by zekth — APPROVED** [review]
:v: great

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I've landed the first one and now this conflicts :(.

**Comment by SimenB** [comment]
@mcollina done!

**Pull request merged**
