### PR TITLE
fix: Unsign cookie, if already signed by cookie plugin

### PR DESCRIPTION
**Pull request by m0dch3n**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [] tests and/or benchmarks are included (I don't know how to test this properly, and I'm also missing the time...)
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by m0dch3n** [comment]
fixes: #69

**Comment by Eomm** [comment]
Would you mind to add a test?

**Review by mcollina — COMMENTED** [review]
Can you please add a unit test?

**Comment by m0dch3n** [comment]
As mentioned [here](https://github.com/fastify/session/issues/69#issuecomment-1076003811), I unfortunately currently do not have time, to do more time investment here. So I would be happy, if someone else can create the test.

You'll find in [the issue comment](https://github.com/fastify/session/issues/69#issuecomment-1074916528) also a Github Repo, where you can see the problem...

**Comment by jsumners** [comment]
> As mentioned [here](https://github.com/fastify/session/issues/69#issuecomment-1076003811), I unfortunately currently do not have time, to do more time investment here. So I would be happy, if someone else can create the test.
> 
> You'll find in [the issue comment](https://github.com/fastify/session/issues/69#issuecomment-1074916528) also a Github Repo, where you can see the problem...

Changes to code are not complete without test coverage. Tossing code at overburdened maintainers and telling them "you do the rest" is not acceptable. The PR will sit until you decide to complete it, or another person with the same problem decides to pick it up.

**Comment by m0dch3n** [comment]
ok, no problem, I just wanted to help, but unfortunately did not have more time, to create proper tests... the existing tests do not fail btw...

**Pull request closed without merging**
