### PR TITLE
fix unit test

### PR DESCRIPTION
**Pull request by Uzlopak**
I really dont know how to describe this issue. I dont know why I need to pass a new Object for register. If I just pass sessionOptions directly then the fixed unit test will fail. Super strange, and makes me wonder if there is any documentation regarding this odd behaviour in fastify core?

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
The tests are not failing on master.

**Comment by Uzlopak** [comment]
@mcollina 

I know they are not failing, but the 'should use custom sessionId generator if available (without request)' test should fail on master. If you comment out all tests before that test, it will fail on master.

**Comment by mcollina** [comment]
I think the problem is that this module is modifying the options object instead of creating a copy of it. Could you make it so?

**Comment by Uzlopak** [comment]
@mcollina 
I made ensureDefaults immutable

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
