### PR TITLE
Add rolling option

### PR DESCRIPTION
**Pull request by AaronPorts**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing

**Comment by mcollina** [comment]
Can you add a test for the type change? you'll find them in types/test

**Comment by zekth** [comment]
Can you add a test with `rolling` and `session.touch()` also?

**Comment by AaronPorts** [comment]
Have added test with `session.touch()`, but I'm a little bit confused about the test for the type change.

**Comment by zekth** [comment]
> Have added test with `session.touch()`, but I'm a little bit confused about the test for the type change.

Indeed those are pretty confusing, i think we should migrate to `tsd` in the future. Just you can recopy the `basic.ts` and add the rolling option to the plugin. Then it would ensure it compiles. (no the best i know)

**Comment by AaronPorts** [comment]
Ok, so should I add `rolling` option to the basic.ts or create a new test file?

**Comment by zekth** [comment]
> Ok, so should I add `rolling` option to the basic.ts or create a new test file?

Create a new with `rolling: false` as default is `true`

**Review by mcollina — APPROVED** [review]
lgtm

**Review by zekth — APPROVED** [review]
lgtm thanks!

**Comment by mcollina** [comment]
@zekth could you ship a new release?

**Comment by zekth** [comment]
@mcollina i don't have permissions on fastify org. Maybe @climba03003 can?

**Pull request merged**
